name: My Starter Workflow

on:
  workflow_dispatch:

jobs:call-reusable-workflow:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: ./.github/workflows/reusable-workflow.yml
      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.
